import Head from "next/head";
import MoreConsultationButton from "src/components/modules/buttons/MoreConsultationButton";
import styles from "../styles/postListPage.module.css";
import ConsultationListArea from "src/components/block/ConsultationListArea";

const consultations = () => {
  return (
    <div>
      <Head>
        <title>恋愛相談一覧 | 恋々</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.title}>恋愛相談</h1>
        <div>
          <ConsultationListArea />
        </div>
        <div className={styles.nextButton}>
          <MoreConsultationButton />
        </div>
      </div>
    </div>
  );
};

export default consultations;
